
server:
  port: 10001
spring:
  application:
    name: tp-usermanager
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
pagehelper:
  auto-dialect: mysql
  support-methods-arguments: true
  reasonable: true