
server:
  port: 9091
spring:
  application:
    name: tp_provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/captain?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
mybatis:
  mapper-locations: classpath:mapping/*.xml